# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

language:
  - cpp

os:
  - linux
  - osx

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
# * http://stackoverflow.com/a/30925448/2288008
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3

      # python3-pip package is not available, use 'easy_install3':
      # * https://github.com/travis-ci/apt-package-whitelist/issues/768
      - python3-setuptools # easy_install3

      # https://github.com/travis-ci-tester/travis-test-clang-cxx-11
      - libstdc++-4.8-dev

      # https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
      - g++-4.8

env:
  global:
    - secure: "IpVQQ3WaLQdSYtZTJFB+/1zJw1Jhli+AuKUfzikeO/EMv1QVD8sOAlsfGkrs/0V/uzLnq3yo8I8VjakGySZW7RquT7JlTF8jIrbvPGltMCL2AGlpmA9fsohXJ3jddWLD1jI9/GP53SZFpA3WHN8PSufbbtVx9snATiYH/c7nebuHz4xZ7uOV6zAIAfeCaqTjxC6NXAjp18bwOcMoSBGy94KmOQK7TqC0+bIFV62V0YXsp/0sC12n80X7mrV3d1K5GXH18akzOyl5/J2UtCsOt47591uu1VG8lfRiq3Hd1Q5zyfc0C74nVuYHUCT0ykT+3eWSO5LA3crY4NXzCXNxJ7tRX6rIT61V56YwSSMm8HgrtMkCplXMLHEtrZlmIVumgn20YUnSUP40Giaib/tv3cyaKPeF1Wv99nqJvd7qnmKl+TcrAiMtM1gGtyih2NgdUoc2ukJv8/Gx3pXQNlzZ2Wg4AEDZW6wHugxtUjFllwM8wmKKdARyLozudB6cfFjw4VBp2EH8xGnRG7RhjuC+XeFl3Z8iKs7TzRxZTosTRSC9SzxVBiPevi4CdVD48CzYpdReoxjhHqX+ZTDlpx0WZ1mmpYQz+dD4vHKl5iUX+SwEItqOIZiDpIw5jVbiiCtEUOI7UBMZHDoPAgHDx63HAKdvIkr5HC3yMoWeDQgy90c="

  matrix:
    # Boost
    - PROJECT_DIR=examples/Boost TOOLCHAIN=default
    - PROJECT_DIR=examples/Boost TOOLCHAIN=libcxx
    - PROJECT_DIR=examples/Boost TOOLCHAIN=clang-libstdcxx
    - PROJECT_DIR=examples/Boost TOOLCHAIN=osx-10-9
    - PROJECT_DIR=examples/Boost TOOLCHAIN=gcc
    - PROJECT_DIR=examples/Boost TOOLCHAIN=gcc-4-8
    - PROJECT_DIR=examples/Boost TOOLCHAIN=ios-nocodesign
    - PROJECT_DIR=examples/Boost TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    - PROJECT_DIR=examples/Boost TOOLCHAIN=analyze
    - PROJECT_DIR=examples/Boost TOOLCHAIN=sanitize-address
    - PROJECT_DIR=examples/Boost TOOLCHAIN=sanitize-leak
    - PROJECT_DIR=examples/Boost TOOLCHAIN=sanitize-thread

    # Boost-filesystem
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=default
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=libcxx
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=clang-libstdcxx
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=osx-10-9
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=gcc
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=gcc-4-8
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=ios-nocodesign
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=analyze
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=sanitize-address
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=sanitize-leak
    - PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=sanitize-thread

    # Boost-system
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=default
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=libcxx
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=clang-libstdcxx
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=osx-10-9
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=gcc
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=gcc-4-8
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=ios-nocodesign
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=analyze
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=sanitize-address
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=sanitize-leak
    - PROJECT_DIR=examples/Boost-system TOOLCHAIN=sanitize-thread

    # Boost-iostreams
    - PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=default
    - PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=libcxx

    # FIXME:
    # * https://travis-ci.org/ingenue/hunter/jobs/105982173
    # - PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=clang-libstdcxx

    - PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=osx-10-9
    - PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=gcc
    - PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=gcc-4-8

    # FIXME:
    # * https://travis-ci.org/ingenue/hunter/jobs/105982177
    # - PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=ios-nocodesign

    # FIXME:
    # * https://travis-ci.org/ingenue/hunter/jobs/105856458
    # - PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon

    # FIXME:
    # * https://travis-ci.org/ingenue/hunter/jobs/105982178
    # * https://travis-ci.org/ingenue/hunter/jobs/105982140
    # - PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=analyze

    - PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=sanitize-address
    - PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=sanitize-leak
    - PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=sanitize-thread

matrix:
  exclude:
    ##### Boost #####
    ### Linux excludes ###
    # https://github.com/travis-ci-tester/travis-test-clang-with-libcxx
    - os: linux
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=libcxx

    # Xcode is for OSX only
    - os: linux
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=osx-10-9
    - os: linux
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=ios-nocodesign

    # https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
    - os: linux
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=gcc

    ### OSX excludes ###
    # TOOLCHAIN=gcc works fine on OSX
    - os: osx
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=gcc-4-8

    # https://github.com/travis-ci-tester/travis-test-mac-clang-address-sanitizer
    - os: osx
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=sanitize-address

    # Linux only
    - os: osx
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=sanitize-leak
    - os: osx
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=sanitize-thread

    ##### Boost-filesystem #####
    ### Linux excludes ###
    # https://github.com/travis-ci-tester/travis-test-clang-with-libcxx
    - os: linux
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=libcxx

    # Xcode is for OSX only
    - os: linux
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=osx-10-9
    - os: linux
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=ios-nocodesign

    # https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
    - os: linux
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=gcc

    ### OSX excludes ###
    # TOOLCHAIN=gcc works fine on OSX
    - os: osx
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=gcc-4-8

    # https://github.com/travis-ci-tester/travis-test-mac-clang-address-sanitizer
    - os: osx
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=sanitize-address

    # Linux only
    - os: osx
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=sanitize-leak
    - os: osx
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=sanitize-thread

    # Broken build:
    # * https://travis-ci.org/ingenue/hunter/jobs/115628636
    - os: osx
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=clang-libstdcxx

    ##### Boost-system #####
    ### Linux excludes ###
    # https://github.com/travis-ci-tester/travis-test-clang-with-libcxx
    - os: linux
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=libcxx

    # Xcode is for OSX only
    - os: linux
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=osx-10-9
    - os: linux
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=ios-nocodesign

    # https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
    - os: linux
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=gcc

    ### OSX excludes ###
    # TOOLCHAIN=gcc works fine on OSX
    - os: osx
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=gcc-4-8

    # https://github.com/travis-ci-tester/travis-test-mac-clang-address-sanitizer
    - os: osx
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=sanitize-address

    # Linux only
    - os: osx
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=sanitize-leak
    - os: osx
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=sanitize-thread

    ##### Boost-iostreams #####
    ### Linux excludes ###
    # https://github.com/travis-ci-tester/travis-test-clang-with-libcxx
    - os: linux
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=libcxx

    # Xcode is for OSX only
    - os: linux
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=osx-10-9
    - os: linux
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=ios-nocodesign

    # https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
    - os: linux
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=gcc

    # FIXME: https://travis-ci.org/ingenue/hunter/jobs/105856455
    - os: linux
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=default

    ### OSX excludes ###
    # TOOLCHAIN=gcc works fine on OSX
    - os: osx
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=gcc-4-8

    # https://github.com/travis-ci-tester/travis-test-mac-clang-address-sanitizer
    - os: osx
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=sanitize-address

    # Linux only
    - os: osx
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=sanitize-leak
    - os: osx
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=sanitize-thread

install:
  # Info about OS
  - uname -a

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then easy_install3 --user requests; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_ROOT="`pwd`/polly-master"
  - export PATH="${POLLY_ROOT}/bin:${PATH}"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"

script:
  - python3 ./jenkins.py --upload
