# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

language:
  - cpp

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

env:
  global:
    - secure: "IpVQQ3WaLQdSYtZTJFB+/1zJw1Jhli+AuKUfzikeO/EMv1QVD8sOAlsfGkrs/0V/uzLnq3yo8I8VjakGySZW7RquT7JlTF8jIrbvPGltMCL2AGlpmA9fsohXJ3jddWLD1jI9/GP53SZFpA3WHN8PSufbbtVx9snATiYH/c7nebuHz4xZ7uOV6zAIAfeCaqTjxC6NXAjp18bwOcMoSBGy94KmOQK7TqC0+bIFV62V0YXsp/0sC12n80X7mrV3d1K5GXH18akzOyl5/J2UtCsOt47591uu1VG8lfRiq3Hd1Q5zyfc0C74nVuYHUCT0ykT+3eWSO5LA3crY4NXzCXNxJ7tRX6rIT61V56YwSSMm8HgrtMkCplXMLHEtrZlmIVumgn20YUnSUP40Giaib/tv3cyaKPeF1Wv99nqJvd7qnmKl+TcrAiMtM1gGtyih2NgdUoc2ukJv8/Gx3pXQNlzZ2Wg4AEDZW6wHugxtUjFllwM8wmKKdARyLozudB6cfFjw4VBp2EH8xGnRG7RhjuC+XeFl3Z8iKs7TzRxZTosTRSC9SzxVBiPevi4CdVD48CzYpdReoxjhHqX+ZTDlpx0WZ1mmpYQz+dD4vHKl5iUX+SwEItqOIZiDpIw5jVbiiCtEUOI7UBMZHDoPAgHDx63HAKdvIkr5HC3yMoWeDQgy90c="

matrix:
  include:
    # Boost {
    # Linux {
    - os: linux
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=default
    - os: linux
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=gcc
    - os: linux
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    - os: linux
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=analyze
    - os: linux
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=sanitize-address
    - os: linux
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=sanitize-leak

    # FIXME: https://github.com/ruslo/hunter/issues/718#issuecomment-290610583
    # - os: linux
    #   env: PROJECT_DIR=examples/Boost TOOLCHAIN=sanitize-thread

    # }

    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=default
    - os: osx
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=libcxx
    - os: osx
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=clang-libstdcxx
    - os: osx
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=osx-10-11
    - os: osx
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=ios-nocodesign-9-3-wo-armv7s
    - os: osx
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=ios-nocodesign-9-3
    - os: osx
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    - os: osx
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=analyze

    - os: osx
      osx_image: xcode8.2
      env: PROJECT_DIR=examples/Boost TOOLCHAIN=cxx11

    # }
    # }

    # Boost-filesystem {
    # Linux {
    - os: linux
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=default
    - os: linux
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=gcc
    - os: linux
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    - os: linux
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=analyze
    - os: linux
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=sanitize-address
    - os: linux
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=sanitize-leak

    # FIXME: https://github.com/ruslo/hunter/issues/718#issuecomment-290610583
    # - os: linux
    #   env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=sanitize-thread

    # }

    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=default
    - os: osx
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=libcxx

    # Broken build:
    # * https://travis-ci.org/ingenue/hunter/jobs/115628636
    # - os: osx
    #   env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=clang-libstdcxx

    - os: osx
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=osx-10-11
    - os: osx
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=ios-nocodesign-9-3-wo-armv7s
    - os: osx
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=ios-nocodesign-9-3
    - os: osx
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    - os: osx
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=analyze

    - os: osx
      osx_image: xcode8.2
      env: PROJECT_DIR=examples/Boost-filesystem TOOLCHAIN=cxx11

    # }
    # }

    # Boost-system {
    # Linux {
    - os: linux
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=default
    - os: linux
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=gcc
    - os: linux
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    - os: linux
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=analyze
    - os: linux
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=sanitize-address
    - os: linux
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=sanitize-leak

    # FIXME: https://github.com/ruslo/hunter/issues/718#issuecomment-290610583
    # - os: linux
    #   env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=sanitize-thread

    # }

    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=default
    - os: osx
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=libcxx
    - os: osx
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=clang-libstdcxx
    - os: osx
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=osx-10-11
    - os: osx
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=ios-nocodesign-9-3-wo-armv7s
    - os: osx
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=ios-nocodesign-9-3
    - os: osx
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    - os: osx
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=analyze

    - os: osx
      osx_image: xcode8.2
      env: PROJECT_DIR=examples/Boost-system TOOLCHAIN=cxx11

    # }
    # }

    # Boost-iostreams {
    # Linux {

    # FIXME: https://travis-ci.org/ingenue/hunter/jobs/105856455
    # - os: linux
    #   env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=default

    # FIXME:
    # * https://travis-ci.org/ingenue/hunter/jobs/105982173
    # - os: linux
    #   env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=clang-libstdcxx

    - os: linux
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=gcc

    # FIXME:
    # * https://travis-ci.org/ingenue/hunter/jobs/105856458
    # - os: linux
    #   env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon

    # FIXME:
    # * https://travis-ci.org/ingenue/hunter/jobs/105982178
    # * https://travis-ci.org/ingenue/hunter/jobs/105982140
    # - os: linux
    #   env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=analyze

    - os: linux
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=sanitize-address
    - os: linux
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=sanitize-leak

    # FIXME: https://github.com/ruslo/hunter/issues/718#issuecomment-290610583
    # - os: linux
    #   env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=sanitize-thread

    # }

    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=default
    - os: osx
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=libcxx

    # FIXME:
    # * https://travis-ci.org/ingenue/hunter/jobs/105982173
    # - os: osx
    #   env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=clang-libstdcxx

    - os: osx
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=osx-10-11

    # FIXME:
    # * https://travis-ci.org/ingenue/hunter/jobs/105982177
    # - os: osx
    #   env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=ios-nocodesign-9-3

    # FIXME:
    # - os: osx
    #   env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=ios-nocodesign-9-3-wo-armv7s

    - os: osx
      env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon

    # FIXME:
    # * https://travis-ci.org/ingenue/hunter/jobs/105982178
    # * https://travis-ci.org/ingenue/hunter/jobs/105982140
    # - os: osx
    #   env: PROJECT_DIR=examples/Boost-iostreams TOOLCHAIN=analyze

    # }
    # }

    # Boost-thread {
    # Linux {
    - os: linux
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=default
    - os: linux
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=gcc
    - os: linux
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    - os: linux
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=analyze
    - os: linux
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=sanitize-address
    - os: linux
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=sanitize-leak

    # FIXME: https://github.com/ruslo/hunter/issues/718#issuecomment-290610583
    # - os: linux
    #   env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=sanitize-thread

    # }

    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=default
    - os: osx
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=libcxx

    # FIXME: https://travis-ci.org/ingenue/hunter/jobs/157828813
    # - os: osx
    #   env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=clang-libstdcxx

    - os: osx
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=osx-10-11
    - os: osx
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=ios-nocodesign-9-3-wo-armv7s
    - os: osx
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=ios-nocodesign-9-3
    - os: osx
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon

    # FIXME: https://travis-ci.org/ingenue/hunter/jobs/157828818
    # - os: osx
    #   env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=analyze

    - os: osx
      osx_image: xcode8.2
      env: PROJECT_DIR=examples/Boost-thread TOOLCHAIN=cxx11

    # }
    # }

    # Boost-chrono {
    # Linux {
    - os: linux
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=default
    - os: linux
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=gcc
    - os: linux
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    - os: linux
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=analyze
    - os: linux
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=sanitize-address
    - os: linux
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=sanitize-leak

    # FIXME: https://github.com/ruslo/hunter/issues/718#issuecomment-290610583
    # - os: linux
    #   env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=sanitize-thread

    # }

    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=default
    - os: osx
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=libcxx
    - os: osx
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=clang-libstdcxx
    - os: osx
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=osx-10-11
    - os: osx
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=ios-nocodesign-9-3-wo-armv7s
    - os: osx
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=ios-nocodesign-9-3
    - os: osx
      env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon

    # FIXME: https://travis-ci.org/ingenue/hunter/jobs/158223572
    # - os: osx
    #   env: PROJECT_DIR=examples/Boost-chrono TOOLCHAIN=analyze

    # }
    # }

    # Boost-serialization {
    # Linux {
    - os: linux
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=default
    - os: linux
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=gcc
    - os: linux
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon

    # FIXME: https://travis-ci.org/ingenue/hunter/jobs/159627884
    # - os: linux
    #   env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=analyze

    - os: linux
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=sanitize-address
    - os: linux
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=sanitize-leak

    # FIXME: https://github.com/ruslo/hunter/issues/718#issuecomment-290610583
    # - os: linux
    #   env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=sanitize-thread

    # }

    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=default
    - os: osx
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=libcxx
    - os: osx
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=clang-libstdcxx
    - os: osx
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=osx-10-11
    - os: osx
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=ios-nocodesign-9-3-wo-armv7s
    - os: osx
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=ios-nocodesign-9-3
    - os: osx
      env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon

    # FIXME: https://travis-ci.org/ingenue/hunter/jobs/159627884
    # - os: osx
    #   env: PROJECT_DIR=examples/Boost-serialization TOOLCHAIN=analyze

    # }
    # }

    # Boost-random {
    - os: linux
      env: PROJECT_DIR=examples/Boost-random TOOLCHAIN=gcc

    - os: osx
      osx_image: xcode8.2
      env: PROJECT_DIR=examples/Boost-random TOOLCHAIN=cxx11
    # }

    # Boost-test {
    - os: linux
      env: PROJECT_DIR=examples/Boost-test TOOLCHAIN=gcc

    - os: osx
      osx_image: xcode8.2
      env: PROJECT_DIR=examples/Boost-test TOOLCHAIN=cxx11
    # }

install:
  # Info about OS
  - uname -a

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then travis_retry pip3 install --user requests; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_ROOT="`pwd`/polly-master"
  - export PATH="${POLLY_ROOT}/bin:${PATH}"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"
  - export ANDROID_NDK_r11c="`pwd`/_ci/android-ndk-r11c"

script:
  - python3 ./jenkins.py --upload

# https://docs.travis-ci.com/user/customizing-the-build/#Whitelisting-or-blacklisting-branches
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - pkg.template
    - /^pr\..*/
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
